version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kh_postgres_dev
    environment:
      POSTGRES_DB: keywordhub_dev
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - kh_db_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d keywordhub_dev"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kh_api_dev
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /tmp:/tmp
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - DISPLAY=:99
      - DEBUG=True
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    command: ["bash", "start.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kh_frontend_dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  kh_db_dev:
