"""Add can_view_all_content field to User model

Revision ID: [auto-generated-id]
Revises: [previous-revision-id]
Create Date: [timestamp]

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = '024_can_view_all_content'
down_revision = '023_cleanup_old_schema'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_view_all_content', sa.Boolean(), nullable=True))

    # Установить значение по умолчанию для существующих записей
    op.execute("UPDATE users SET can_view_all_content = false WHERE can_view_all_content IS NULL")

    # Сделать поле NOT NULL после установки значений по умолчанию
    op.alter_column('users', 'can_view_all_content', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_view_all_content')
    # ### end Alembic commands ###